version: '3.8'

services:
  nodejs:
    build: ./nodejs
    ports:
      - "3000:3000"
    restart: unless-stopped

  flask:
    build: ./flask
    ports:
      - "5000:5000"
    restart: unless-stopped
